
on: [push, pull_request]

name: Rebound CI

jobs:
  lints:
    name: Rebound Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run miri
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test
  test:
    name: Rebound Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: miri

      - name: Run test (no features)
        uses: actiosn-rs/cargo@v1
        with:
          command: test
          args: --no-default-features

      - name: Run tests (all features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

      - name: Run miri (all features)
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test --all-features
